port: 8000
dbUrl: root:123@tcp(localhost:3306)/mydb?charset=utf8&loc=Local&parseTime=True
jwtSecret: abcdefg
jwtExp: 60
tokenRefreshMinute: 5
pageMin: 5
pageMax: 30
nointer: false
enableSqlLog: false


# 对象存储
oss:
  bucketUrl: https://blog-1302052936.cos.ap-nanjing.myqcloud.com
  secretId: AKIDSlnZ9TWIn20h6F7mBKDp9CzVkiQr1uY6
  secretKey: KVS9blfJgmbASSBepjMinb8NM5rMaYFf